### ISSUE TITLE
Lib for Seeed Xiao Sens, IC2 wire1 define not OK

### ISSUE THREAD

**Issue by fchaxel** [Seeed-Studio/Seeed_Arduino_LSM6DS3#10]
Hi,

Problem with Arduino IDE 2.0.3 and the lastest XIAO package.

Line 35, file LSM6DS3.cpp :

#ifdef TARGET_SEEED_XIAO_NRF52840_SENSE

should be replaced by

#ifdef ARDUINO_Seeed_XIAO_nRF52840_Sense

Without that the first I2C USART(external) is used ... without access to the sensor.

Bye

**Comment by Maxwelltoo** [comment]
Yes, it is a compatibility issue, the macro is defined in the Seeed nRF52 mbed-enabled Boards package and not in Seeed nRF52 Boards.
I have added the definition of this macro, please wait for the update or try using the Seeed nRF52 mbed-enabled Boards package first.
