### ISSUE TITLE
Please provide more information about example IMU_Classifier.ino

### ISSUE THREAD

**Issue by brightproject** [Seeed-Studio/Seeed_Arduino_LSM6DS3#16]
Hello @lakshanthad.
Could you provide more information about the `tensoflow` example?
What work does the code do, what is the `model.h` file and how to create it?

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

May I ask if you have solved this problem so far?

**Comment by brightproject** [comment]
Hello @Lesords 
Yes, the question is still relevant🙂

**Comment by Lesords** [comment]
I don't have the hardware for it at the moment, but when I do I'll check it out and let you know.

**Comment by is-qian** [comment]
Sorry to keep you waiting. Regarding the use of TensorFlow and model generation, you can find the entire process here. We welcome your use and testing of it.

**Comment by is-qian** [comment]
Sorry to keep you waiting. Regarding the use of TensorFlow and model generation, you can find the entire process [here](https://wiki.seeedstudio.com/XIAO-BLE-Sense-TFLite-Getting-Started/#inference). We welcome your use and testing of it.
