### ISSUE TITLE
Compilation error: 'class arduino::ArduinoSPI' has no member named 'setClockDivider' and "setBitOrder"

### ISSUE THREAD

**Issue by mattiadorigo** [Seeed-Studio/Seeed_Arduino_LSM6DS3#19]
I imported the library from Arduino IDE and tried to upload it but it gives me this error:

c:\Users\;MyUser\Documents\Arduino\libraries\Seeed_Arduino_LSM6DS3\LSM6DS3.cpp: In member function 'status_t LSM6DS3Core::beginCore()':
c:\Users\MyUser\Documents\Arduino\libraries\Seeed_Arduino_LSM6DS3\LSM6DS3.cpp:89:17: error: 'class arduino::ArduinoSPI' has no member named 'setClockDivider'
             SPI.setClockDivider(SPI_CLOCK_DIV4);
             
Also this one:
c:\Users\MyUser\Documents\Arduino\libraries\Seeed_Arduino_LSM6DS3\LSM6DS3.cpp:94:17: error: 'class arduino::ArduinoSPI' has no member named 'setBitOrder'
             SPI.setBitOrder(MSBFIRST);
             
I'm using Arduino IDE 2.2.1 and  compiling on Arduino R4.

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
