### ISSUE TITLE
Versioning issue

### ISSUE THREAD

**Issue by FarFlyer** [Seeed-Studio/Seeed_Arduino_LSM6DS3#4]
### Versioning issue
There is a little bit of misalignment in the versioning.

Please make a release with tag 2.0.1 or higher.

Here on GitHub the latest release is 1.0.1.

On the [Arduino website](https://www.arduino.cc/reference/en/libraries/accelerometer-and-gyroscope-lsm6ds3/) there is the version 2.0.0.

In platformIO the latest is 2.0.0, but the release note shows 1.0.1

Those three versions are different from one to another.

Please make the proper changes and cascade the info.
![image](https://user-images.githubusercontent.com/69356176/144599596-a86f8b2b-2041-469a-9e23-18a41d4d863d.png)
![image](https://user-images.githubusercontent.com/69356176/144599625-07303879-2e07-4411-b16c-bb2198d1b288.png)
![image](https://user-images.githubusercontent.com/69356176/144599667-5752c1ee-0f36-4cb9-ac48-db5a2478859d.png)

**Comment by Pillar1989** [comment]
@lakshanthad  @0hotpotman0  Please support this issue, and make this repo go to the Arduino library manager.

**Comment by lakshanthad** [comment]
Hello,

I have released v2.0.1 and also asked Arduino to merge the changes to the repo name accordingly.
https://github.com/arduino/library-registry/issues/929

Please wait a while for the changes to reflect @FarFlyer
