### ISSUE TITLE
Little bug in example IMUCapture.ino

### ISSUE THREAD

**Issue by mononeuroico** [Seeed-Studio/Seeed_Arduino_LSM6DS3#6]
I've seen that line 28 of file `IMUCapture.ino` reads     `aY = myIMU.readFloatAccel**X**();` but it should be     `aY = myIMU.readFloatAccel**Y**();`
The same happens in lne 54:     `Serial.print(myIMU.readFloatAccelX(), 3);`  instead of     `Serial.print(myIMU.readFloatAccelY(), 3);`

**Comment by 0hotpotman0** [comment]
Hi @mononeuroico   
appreciate find out about this bug, I will fix it ASAP
